### PR TITLE
636 link case studies in our work

### PR DESCRIPTION
**Pull request by hannahouazzane**
#636 
Adds case study links to  project cards on the Our Work page.

### CODE REVIEW

**Comment by harryharrold** [comment]
@rachelpeharding - could you check positioning and styling of these links?

**Comment by rachelpeharding** [comment]
> @rachelpeharding - could you check positioning and styling of these links?

I wonder if we should style the links as buttons and reduce the length of copy? I'd probably add some more spacing between the image and the link at the least.

**Comment by jermyk** [comment]
Yes, good plan.

The copy was for accessibility - is there another way we can tell a screen
reader where the link goes without duplicating link text?

**Comment by hannahouazzane** [comment]
> > @rachelpeharding - could you check positioning and styling of these links?
> 
> I wonder if we should style the links as buttons and reduce the length of copy? I'd probably add some more spacing between the image and the link at the least.

Sounds like a good plan! Will do this in my local and share with you all

**Pull request merged**
