### PR TITLE
Delete kat.md

### PR DESCRIPTION
**Pull request by harryharrold**
Fixes #

## Description

- As it says.
-

### CODE REVIEW

**Comment by Nikomus** [comment]
Don't forget to also remove the [profile image](https://github.com/neontribe/www/blob/kat-leaving/src/data/tribers/images/Kat.jpg) too.

**Comment by harryharrold** [comment]
> Don't forget to also remove the [profile image](https://github.com/neontribe/www/blob/kat-leaving/src/data/tribers/images/Kat.jpg) too.

Ah.

I don't know how to do that....

**Comment by Nikomus** [comment]
> > Don't forget to also remove the [profile image](https://github.com/neontribe/www/blob/kat-leaving/src/data/tribers/images/Kat.jpg) too.
> 
> Ah.
> 
> I don't know how to do that....

Go to the link and use the [ … ] menu. You can see you're in the same branch as these changes from the dropdown on the left. I could do it but then I can't approve the PR..


image

**Comment by harryharrold** [comment]
wrong or permissions

....am I in the wrong place, or do I have a permissions issue? @Nikomus

**Comment by harryharrold** [comment]
Found it - file deleted. @nikomus

**Review by rosejbon — APPROVED** [review]

**Review by Nikomus — APPROVED** [review]
Looks good 👍

**Pull request merged**
