### PR TITLE
Update gatsby-config.js

### LINKED ISSUE #590: Tab Theme Colour
**What needs doing?**
On some mobile browsers (Chrome, Samsung, etc) the meta theme-color tag is used to colour the tab. We're using the old purple theme colour here rather than the newer one in use since the redesign.

image

**Plan**
- [ ] Update the meta tag to the new colour!

**Acceptance Criteria**
- [ ] On browsers that use themed tabs, the colour matches the new colour scheme.

### PR DESCRIPTION
**Pull request by Nikomus**
Fixes #590 

Updates the theme colour!

### CODE REVIEW

**Review by neonleann — APPROVED** [review]
🎩

**Review by harryharrold — APPROVED** [review]
...how did it ever get purple?

**Comment by Nikomus** [comment]
> ...how did it ever get purple?

It was meant to be purple, but it was the old purple!

image

**Comment by harryharrold** [comment]
I'm sure that's more a blurple.

**Pull request merged**
