### PR TITLE
Remove george from the website 😢

### PR DESCRIPTION
**Pull request by robpre**
as per leavers policy

### CODE REVIEW

**Comment by katjam** [comment]
Do we want to remove the blog image?

**Comment by katjam** [comment]
Alex and Holly and Andy still in. I think we can consider it achieved info/data and therefore should remain intact?

**Comment by robpre** [comment]
I believe this image is from the old website's profile page, it isn't referenced in any blog posts. I don't think we should remove George from the blog posts.

**Comment by katjam** [comment]
Yes I also think it is the old profile page. We have left everyone else
intact there.

**Comment by harryharrold** [comment]
@Nikomus Good call - I'd surprised if we never touched the design again.

**Pull request merged**
