### PR TITLE
Initial Gatsby site created

### PR DESCRIPTION
**Pull request by Nikomus**
A fresh, default Gatsby site. I'm sharding off the WP integration until the WP.com site is set up.

https://trello.com/c/jCUP5uI3/74-spin-up-a-gatsby-repo

### CODE REVIEW

**Comment by katjam** [comment]
@marxian suggestions sound perfectly sensible. Particularly on improving the README & getting a standard linting setup.

**Comment by marxian** [comment]
@katjam I'd also like us to consider adding commit message linting...

**Comment by katjam** [comment]
Yes - and - do you agree with these guidelines?
https://chris.beams.io/posts/git-commit/#seven-rules

**Comment by marxian** [comment]
@katjam Yes I agree with most of those guidelines.

I also like to see a type and a scope to assist in building nice changelogs and calculating release numbers.

**Comment by katjam** [comment]
We did some work around changelogs and release numbers in cottages - @Toby
Batch <tobias@neontribe.co.uk> may have some input from his experiences.
Ticket it as a nice to have infrastructure card... and one day we may
prioritise. Agree that this project will be a good place to try stuff out
and discover good practices.

**Pull request merged**
