### PR TITLE
Jan 2022 package updates

### PR DESCRIPTION
**Pull request by Nikomus**
## Description

- Updates for all patch and minor versions
- A couple larger updates and yarn / node versions
- Fix tests
- Make logo image square to supress build warning

### CODE REVIEW

**Review by charlesstrange2 — APPROVED** [review]
⛏️ groovey

**Review by robpre — APPROVED** [review]
:badger: :badger: :badger: :badger: :badger: :badger: :badger: :badger: :badger: :badger: :badger: :badger: :mushroom: :mushroom:

**Comment by charlesstrange2** [comment]
> 🦡 🦡 🦡 🦡 🦡 🦡 🦡 🦡 🦡 🦡 🦡 🦡 🍄 🍄

🐍!! 👀

**Comment by harryharrold** [comment]
:trollface:s, the pair of you.

**Pull request merged**
